#version 450
precision highp float;
precision highp int;
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D flowDense;
layout(set = 0, binding = 5, rgba16f) writeonly uniform image2D outImage;
void main() {
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outImage);
    if (pix.x >= size.x || pix.y >= size.y) return;
    vec2 flow = texelFetch(flowDense, pix, 0).xy;
    imageStore(outImage, pix, vec4(flow, 0.0, 1.0));
}
