#version 450
precision highp float;
precision highp int;
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D srcImage;
layout(set = 0, binding = 5, r32f) writeonly uniform image2D dstImage;
void main() {
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dstSize = imageSize(dstImage);
    if (pix.x >= dstSize.x || pix.y >= dstSize.y) return;
    vec2 uv = (vec2(pix) + 0.5) / vec2(dstSize);
    float val = textureLod(srcImage, uv, 0.0).x;
    imageStore(dstImage, pix, vec4(val, 0.0, 0.0, 1.0));
}
